// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGNW2-jxW2mKX-ONbLVG6nls99lH6gcHw',
    appId: '1:910818151686:web:df6386d0388de2c595a287',
    messagingSenderId: '910818151686',
    projectId: 'formulandapp',
    authDomain: 'formulandapp.firebaseapp.com',
    storageBucket: 'formulandapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_iNKBGgB3CX3HOqSf4CZd6iJY1xZ-Nw',
    appId: '1:910818151686:android:c083730f3ec7ac6a95a287',
    messagingSenderId: '910818151686',
    projectId: 'formulandapp',
    storageBucket: 'formulandapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGNW2-jxW2mKX-ONbLVG6nls99lH6gcHw',
    appId: '1:910818151686:web:6a53c3981bdac46795a287',
    messagingSenderId: '910818151686',
    projectId: 'formulandapp',
    authDomain: 'formulandapp.firebaseapp.com',
    storageBucket: 'formulandapp.firebasestorage.app',
  );
}
